# Generated by Django 2.1.12 on 2019-09-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.BinaryField(),
        ),
    ]
