# Generated by Django 2.1.12 on 2019-09-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0005_auto_20190920_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='title',
            new_name='caption',
        ),
        migrations.AddField(
            model_name='image',
            name='owner',
            field=models.CharField(default='test', max_length=60),
            preserve_default=False,
        ),
    ]
