# Generated by Django 2.1.12 on 2019-09-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0006_auto_20190920_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
