# Generated by Django 2.1.12 on 2019-09-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0007_auto_20190921_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
