# Generated by Django 2.1.12 on 2019-09-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artid', models.IntegerField()),
                ('content', models.TextField(blank=True, verbose_name='Article Content')),
            ],
        ),
    ]
