# Generated by Django 2.1.12 on 2019-09-11 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='artid',
        ),
    ]
