# Generated by Django 2.1.12 on 2019-09-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_article_artid'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='owner',
            field=models.CharField(default='xx', max_length=60),
            preserve_default=False,
        ),
    ]
