# Generated by Django 2.1.12 on 2019-09-12 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_article_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
